# Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

# You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

# For example:

# .......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

# .......S.......
# .......|.......
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# At that point, the original beam stops, and two new beams are emitted from the splitter:

# .......S.......
# .......|.......
# ......|^|......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# Those beams continue downward until they reach more splitters:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# .....|^|^|.....
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# This process continues until all of the tachyon beams reach a splitter or exit the manifold:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# .....|^|^|.....
# .....|.|.|.....
# ....|^|^|^|....
# ....|.|.|.|....
# ...|^|^|||^|...
# ...|.|.|||.|...
# ..|^|^|||^|^|..
# ..|.|.|||.|.|..
# .|^|||^||.||^|.
# .|.|||.||.||.|.
# |^|^|^|^|^|||^|
# |.|.|.|.|.|||.|
# To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

# Analyze your manifold diagram. How many times will the beam be split?

def parse_input(input):
    grid = []
    for line in input.strip().split("\n"):
        grid.append(list(line))
    return grid

def count_beam_splits(grid):
    rows = len(grid)
    cols = len(grid[0])
    beam_splits = 0
    return beam_splits

def main():
    with open("data/day_8_input.txt") as f:
        input_data = f.read()
    grid = parse_input(input_data)
    result = count_beam_splits(grid)
    print(f"Number of beam splits: {result}")

if __name__ == "__main__":
    main()