# Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

# You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

# For example:

# .......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

# .......S.......
# .......|.......
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# At that point, the original beam stops, and two new beams are emitted from the splitter:

# .......S.......
# .......|.......
# ......|^|......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# Those beams continue downward until they reach more splitters:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# .....|^|^|.....
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# This process continues until all of the tachyon beams reach a splitter or exit the manifold:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# .....|^|^|.....
# .....|.|.|.....
# ....|^|^|^|....
# ....|.|.|.|....
# ...|^|^|||^|...
# ...|.|.|||.|...
# ..|^|^|||^|^|..
# ..|.|.|||.|.|..
# .|^|||^||.||^|.
# .|.|||.||.||.|.
# |^|^|^|^|^|||^|
# |.|.|.|.|.|||.|
# To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

# Analyze your manifold diagram. How many times will the beam be split?

from collections import Counter

def parse_input(input):
    grid = []
    for line in input.strip().split("\n"):
        grid.append(list(line))
    return grid

def count_beam_splits(grid):
    rows = len(grid)
    cols = len(grid[0])
    
    # Find the starting position 'S'
    start_row = 0
    start_col = 0
    for i in range(rows):
        for j in range(cols):
            if grid[i][j] == 'S':
                start_row = i
                start_col = j
                break
    
    # Track active beams: each beam is (row, col)
    # Beams at the same position merge into one
    active_beams = set([(start_row, start_col)])
    # Track which splitters have been hit (each splitter counts once)
    hit_splitters = set()
    beam_splits = 0
    
    # Simulate beam propagation step by step
    # At each step, all beams move down one position
    # When a beam hits a splitter, it's removed and two new beams are created
    while active_beams:
        next_beams = set()
        
        for beam_row, beam_col in active_beams:
            # Move beam down one position
            next_row = beam_row + 1
            
            # Check if beam exits the grid
            if next_row >= rows:
                continue
            
            # Check what the beam hits at the next position
            if grid[next_row][beam_col] == '^':
                # Check if we've already counted this splitter
                splitter_pos = (next_row, beam_col)
                if splitter_pos not in hit_splitters:
                    hit_splitters.add(splitter_pos)
                    beam_splits += 1
                
                # Create two new beams at left and right of splitter
                left_col = beam_col - 1
                right_col = beam_col + 1
                
                # New beams are created at the splitter's row
                if left_col >= 0:
                    next_beams.add((next_row, left_col))
                if right_col < cols:
                    next_beams.add((next_row, right_col))
            else:
                # Beam passes through empty space, continue downward
                next_beams.add((next_row, beam_col))
        
        # Now process any beams that were created at splitter positions
        # (they need to be handled immediately if they're also at splitters)
        final_beams = set()
        beams_to_check = list(next_beams)
        
        while beams_to_check:
            beam_row, beam_col = beams_to_check.pop(0)
            
            # Check if this beam is at a splitter position
            if grid[beam_row][beam_col] == '^':
                # Check if we've already counted this splitter
                splitter_pos = (beam_row, beam_col)
                if splitter_pos not in hit_splitters:
                    hit_splitters.add(splitter_pos)
                    beam_splits += 1
                
                # Create two new beams at left and right
                left_col = beam_col - 1
                right_col = beam_col + 1
                
                if left_col >= 0:
                    beams_to_check.append((beam_row, left_col))
                if right_col < cols:
                    beams_to_check.append((beam_row, right_col))
            else:
                # Beam is at empty space, add it to final beams
                final_beams.add((beam_row, beam_col))
        
        active_beams = final_beams
    
    return beam_splits

# --- Part Two ---
# With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

# With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

# Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

# To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

# In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ...|^.^...^....
# ...|...........
# ..|^.^...^.^...
# ..|............
# .|^...^.....^..
# .|.............
# |^.^.^.^.^...^.
# |..............
# Or, there's the timeline where the particle alternated going left and right at each splitter:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# ......^|^......
# .......|.......
# .....^|^.^.....
# ......|........
# ....^.^|..^....
# .......|.......
# ...^.^.|.^.^...
# .......|.......
# ..^...^|....^..
# .......|.......
# .^.^.^|^.^...^.
# ......|........
# Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ....^|^...^....
# .....|.........
# ...^.^|..^.^...
# ......|........
# ..^..|^.....^..
# .....|.........
# .^.^.^|^.^...^.
# ......|........
# In this example, in total, the particle ends up on 40 different timelines.

# Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?


def count_timelines(grid):
    rows = len(grid)
    cols = len(grid[0])
    
    # Find the starting position 'S' and build splitters map
    start_row = 0
    start_col = 0
    splitters = {}  # row -> set of columns with splitters
    
    for i in range(rows):
        for j in range(cols):
            if grid[i][j] == 'S':
                start_row = i
                start_col = j
            if grid[i][j] == '^':
                if i not in splitters:
                    splitters[i] = set()
                splitters[i].add(j)
    
    # Use memoization to cache results
    # Returns the number of timelines (total paths) reachable from (r, c)
    from functools import cache
    
    @cache
    def recurse(r: int, c: int) -> int:
        """Returns the number of timelines (total paths) reachable from (r, c)"""
        # If we've reached the bottom, this is one timeline
        if r >= rows:
            return 1
        
        # If there's no splitter at this position, continue straight down
        if r not in splitters or c not in splitters[r]:
            return recurse(r + 1, c)
        
        # If there is a splitter, split into left and right paths
        result = 0
        if c - 1 >= 0:
            result += recurse(r + 1, c - 1)
        if c + 1 < cols:
            result += recurse(r + 1, c + 1)
        return result
    
    # Start from the row below S (since beam moves down from S)
    return recurse(start_row + 1, start_col)

def main():
    with open("data/day_8_input.txt") as f:
        input_data = f.read()
    grid = parse_input(input_data)
    
    # Part 1
    result1 = count_beam_splits(grid)
    print(f"Number of beam splits: {result1}")
    
    # Part 2
    result2 = count_timelines(grid)
    print(f"Number of timelines: {result2}")

if __name__ == "__main__":
    main()  
